version: '3.8'

services:
  whispermind:
    build: .
    ports:
      - "3009:3009"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEXT_PUBLIC_APP_URL=http://localhost:3009
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3009/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可選：添加 Nginx 反向代理
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - whispermind
    restart: unless-stopped
    profiles:
      - production
